/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2024 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : r9a02g021_native.c
*  Description  : Main Program
*  Creation Date: 2025-03-29
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include "platform_internal.h"
#include "image_app.h"

#define CPU_CYCLE_ENABLE 	1
#define LOG_ENABLE 			0

#if CPU_CYCLE_ENABLE == 1
size_t cpu_cycle_start = 0;
size_t cpu_cycle_end = 0;
size_t cpu_cycle_app_start = 0;
size_t cpu_cycle_app_end = 0;
#endif

void *
native_main()
{
#if CPU_CYCLE_ENABLE == 1
    cpu_cycle_start = renesas_get_cpu_cycle();
#endif

    image_app_main();

#if CPU_CYCLE_ENABLE == 1
    cpu_cycle_end = renesas_get_cpu_cycle();
#endif

    return NULL;
}


int main(void)
{
	os_printf("Starting Native...\n");

	native_main();

#if CPU_CYCLE_ENABLE == 1
    size_t cpu_cycle_app = cpu_cycle_end - cpu_cycle_start;
    os_printf("Renesas_Native: Load   0\n");
    os_printf("Renesas_Native: Run    %d\n", cpu_cycle_app);
    os_printf("Renesas_Native: Unload 0\n");
    os_printf("Renesas_Native: Total  %d\n", cpu_cycle_app);
#endif

    os_printf("Completed!\n\n");

    return 0;
}
