/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2024 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : r9a02g021_lua.c
*  Description  : Main Program
*  Creation Date: 2025-04-05
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include "platform_internal.h"

// Lua runtime
#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"

// Lua application
#include "../../../applications/image_app_lua/image_app_lua.h"

#define LUA_MAIN_STACK_SIZE 5120
#define CPU_CYCLE_ENABLE 1
#define LOG_ENABLE 0
#define LOG_TAG "Lua"

size_t cpu_cycle_start = 0;
size_t cpu_cycle_end = 0;
size_t cpu_cycle_app_start = 0;
size_t cpu_cycle_app_end = 0;

void *
run_embedded_lua(void)
{
#if CPU_CYCLE_ENABLE == 1
    cpu_cycle_start = renesas_get_cpu_cycle();
#endif

    const char *lua_script = (const char*)image_app_lua;
    size_t lua_script_len = (size_t)image_app_lua_len;

    lua_State *L = luaL_newstate();
    if (L == NULL)
    {
        os_printf("Failed to create new Lua state\n");
        return NULL;
    }

    luaL_openlibs(L);
    if (luaL_loadbuffer(L, lua_script, lua_script_len, "lua_script") != LUA_OK)
    {
    	os_printf("Error loading Lua script: %s\n", lua_tostring(L, -1));
        lua_pop(L, 1);
        lua_close(L);
        return NULL;
    }

#if CPU_CYCLE_ENABLE == 1
    cpu_cycle_app_start = renesas_get_cpu_cycle();
#endif
    if (lua_pcall(L, 0, LUA_MULTRET, 0) != LUA_OK)
    {
    	os_printf("Error running Lua script: %s\n", lua_tostring(L, -1));
        lua_pop(L, 1);
    }
#if CPU_CYCLE_ENABLE == 1
    cpu_cycle_app_end = renesas_get_cpu_cycle();
#endif

    lua_close(L);

#if CPU_CYCLE_ENABLE == 1
    cpu_cycle_end = renesas_get_cpu_cycle();
#endif
    return NULL;
}

//=======================================================
int main(void)
{
	os_printf("Starting running Lua app ...\n");
	run_embedded_lua();
	os_printf("Exiting...\n");
    return 0;
}

