/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2024 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : r9a02g021_wamr_interp_classic_C.c
*  Description  : Main Program
*  Creation Date: 2025-03-28
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include <stdio.h>
#include <stdint.h>
#include "bh_platform.h"
#include "wasm_export.h"

/* Wasm compiled from C */
#include "../../../applications/image_app_c/image_app_wasm.h"

#define CPU_CYCLE_ENABLE 	1
#define LOG_ENABLE 			0
#define WASM_DEFAULT_STACK_SIZE			 256+384
#define WASM_HOST_MANAGED_HEAP_SIZE 	 256

#if CPU_CYCLE_ENABLE == 1
size_t cpu_cycle_start = 0;
size_t cpu_cycle_end = 0;
size_t cpu_cycle_app_start = 0;
size_t cpu_cycle_app_end = 0;
#endif


static void *
app_instance_main(wasm_module_inst_t module_inst)
{
    const char *exception;
    wasm_application_execute_main(module_inst, 0, NULL);
    if ((exception = wasm_runtime_get_exception(module_inst)))
        os_printf("%s\n", exception);
    return NULL;
}


void
iwasm_main()
{
#if CPU_CYCLE_ENABLE == 1
    cpu_cycle_start = renesas_get_cpu_cycle();
#endif

    wasm_module_t wasm_module = NULL;
    wasm_module_inst_t wasm_module_inst = NULL;
    char error_buf[128];
    void *ret;

    /* Configure memory allocation */
    RuntimeInitArgs init_args;
    memset(&init_args, 0, sizeof(RuntimeInitArgs));
    init_args.mem_alloc_type = Alloc_With_Allocator;
	init_args.mem_alloc_option.allocator.malloc_func = (void *)os_malloc;
	init_args.mem_alloc_option.allocator.realloc_func = (void *)os_realloc;
	init_args.mem_alloc_option.allocator.free_func = (void *)os_free;

    /* Wasm application */
    uint8_t *wasm_file_buf = (uint8_t *)wasm_application_file;
    unsigned wasm_file_buf_size = sizeof(wasm_application_file);

    /* Initialize Wasm runtime: Full init */
#if LOG_ENABLE == 1
	os_printf("WAMR: Initialize Wasm runtime\n");
#endif
    if (!wasm_runtime_full_init(&init_args))
    {
    	os_printf("WAMR: Init runtime failed.\n");
        return;
    }

#if LOG_ENABLE == 1
    os_printf("WAMR: Run WAMR with Classic Interpreter\n");
#endif

    /* Load Wasm module */
    if (!(wasm_module = wasm_runtime_load(wasm_file_buf, wasm_file_buf_size, error_buf, sizeof(error_buf))))
    {
    	os_printf("WAMR: Error in wasm_runtime_load: %s\n", error_buf);
        goto fail_1;
    }

    /* Instantiate Wasm runtime */
#if LOG_ENABLE == 1
    os_printf("WAMR: Instantiate Wasm runtime\n");
#endif
    if (!(wasm_module_inst = wasm_runtime_instantiate(wasm_module,
    		(uint32_t)WASM_DEFAULT_STACK_SIZE, (uint32_t)WASM_HOST_MANAGED_HEAP_SIZE,
				error_buf, sizeof(error_buf))))
    {
    	os_printf("WAMR: Error while instantiating: %s\n", error_buf);
        goto fail_2;
    }

    /* Run Wasm application */
#if LOG_ENABLE == 1
    os_printf("WAMR: Run main() of the application\n");
#endif
#if CPU_CYCLE_ENABLE == 1
	cpu_cycle_app_start = renesas_get_cpu_cycle();
#endif
    ret = app_instance_main(wasm_module_inst);
    assert(!ret);
#if CPU_CYCLE_ENABLE == 1
	cpu_cycle_app_end = renesas_get_cpu_cycle();
#endif

    /* Destroy the module instance */
#if LOG_ENABLE == 1
	os_printf("WAMR: Deinstantiate WASM runtime\n");
#endif
    wasm_runtime_deinstantiate(wasm_module_inst);

fail_2:
    /* unload the module */
#if LOG_ENABLE == 1
	os_printf("WAMR: Unload WASM module\n");
#endif
    wasm_runtime_unload(wasm_module);

fail_1:
    /* destroy runtime environment */
#if LOG_ENABLE == 1
    os_printf("WAMR: Destroy WASM runtime\n");
#endif
    wasm_runtime_destroy();

#if CPU_CYCLE_ENABLE == 1
    cpu_cycle_end = renesas_get_cpu_cycle();
#endif
    return;
}

/*=======================================================================*/

int main(void)
{
	os_printf("Starting WAMR-Classic Interpreter mode, Wasm app compiled from C..\n");
	renesas_heap_init_eccram();
	renesas_heap_init_ram();
	//renesas_heap_print_info();

	iwasm_main();

#if CPU_CYCLE_ENABLE == 1
    size_t cpu_cycle_load = cpu_cycle_app_start - cpu_cycle_start;
    size_t cpu_cycle_app = cpu_cycle_app_end - cpu_cycle_app_start;
    size_t cpu_cycle_unload = cpu_cycle_end - cpu_cycle_app_end;
    os_printf("Renesas_WAMR_CI_C: Load   %d\n", cpu_cycle_load);
    os_printf("Renesas_WAMR_CI_C: Run    %d\n", cpu_cycle_app);
    os_printf("Renesas_WAMR_CI_C: Unload %d\n", cpu_cycle_unload);
    os_printf("Renesas_WAMR_CI_C: Total  %d\n", cpu_cycle_load + cpu_cycle_app + cpu_cycle_unload);
#endif

    os_printf("Completed!\n\n");

    return 0;
}
